local LAYER_BLEND_MODE_OVERRIDE = 1

local PARAMETER_TYPE_NUMBER = 1
local PARAMETER_TYPE_BOOLEAN = 2
local PARAMETER_TYPE_TRIGGER = 3

local TRANSITION_BLEND_CURVE_LINEAR = 1

local INTERRUPT_NONE = 1
local INTERRUPT_ANY = 2
local INTERRUPT_HIGHER_PRIORITY = 3

return {
    LAYER_BLEND_MODE_OVERRIDE = LAYER_BLEND_MODE_OVERRIDE,

    LAYER_BLEND_MODES = {
        LAYER_BLEND_MODE_OVERRIDE
    },

    TRANSITION_BLEND_CURVE_LINEAR = TRANSITION_BLEND_CURVE_LINEAR,

    TRANSITION_BLEND_CURVES = {
        TRANSITION_BLEND_CURVE_LINEAR
    },

    PARAMETER_TYPE_NUMBER = PARAMETER_TYPE_NUMBER,
    PARAMETER_TYPE_BOOLEAN = PARAMETER_TYPE_BOOLEAN,
    PARAMETER_TYPE_TRIGGER = PARAMETER_TYPE_TRIGGER,

    INTERRUPT_NONE = INTERRUPT_NONE,
    INTERRUPT_ANY = INTERRUPT_ANY,
    INTERRUPT_HIGHER_PRIORITY = INTERRUPT_HIGHER_PRIORITY
}